services:
  - type: web
    name: joey-ai-frontend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-agent.89115053.xyz
      - key: NEXTAUTH_URL
        value: https://joey-ai-frontend.onrender.com
    healthCheckPath: /
